In [2]:
# ==============================
# WHATWEB COMMAND PREDICTION MODEL
# ==============================

# Install required libraries
# pip install pandas scikit-learn joblib

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
import joblib

# ==========================================
# CREATE DATASET
# ==========================================

data = {
    "command": [

        "whatweb --version",
        "whatweb -h",
        "whatweb example.com",
        "whatweb https://google.com",
        "whatweb -v example.com",
        "whatweb -a 3 example.com",
        "whatweb -a 4 example.com",
        "whatweb google.com github.com reddit.com",
        "whatweb 192.168.1.1",
        "whatweb 192.168.1.0/24",
        "whatweb -i targets.txt",
        "whatweb example.com --log-verbose=output.txt",
        "whatweb example.com --log-json=output.json",
        "whatweb example.com --log-xml=output.xml",
        "whatweb --proxy 127.0.0.1:8080 example.com",
        "whatweb -U Mozilla/5.0 example.com",
        "whatweb -H Authorization:BearerToken example.com",
        "whatweb -c PHPSESSID=12345 example.com",
        "whatweb -u admin:password example.com",
        "whatweb -l",
        "whatweb --search-plugins wordpress",
        "whatweb -I wordpress",
        "whatweb -p wordpress example.com",
        "whatweb -p apache,wordpress,jquery example.com",
        "whatweb --grep WordPress example.com",
        "whatweb -q example.com",
        "whatweb --no-errors 192.168.1.0/24",
        "whatweb --follow-redirect always example.com",
        "whatweb --max-redirects 5 example.com",
        "whatweb -t 50 192.168.1.0/24",
        "whatweb --open-timeout 10 example.com",
        "whatweb --wait 2 example.com",
        "whatweb --debug example.com",
        "whatweb -a 3 -v -t 50 --log-json=scan.json example.com",
        "whatweb https://wordpress.org",
        "whatweb https://www.joomla.org",
        "whatweb https://nginx.org"

    ],

    "output": [

        "WhatWeb version 0.5.5",
        "Usage: whatweb [options] <URLs>",
        "http://example.com [200 OK] Apache, HTML5",
        "https://google.com [200 OK] GFE, HTML5",
        "Status : 200 OK Title : Example Domain IP : 93.184.216.34 Plugins : Apache HTML5",
        "example.com [200 OK] Apache[2.4.54], PHP[8.1], JQuery",
        "Heavy scan mode enabled Apache, PHP, JQuery, Bootstrap",
        "google.com [200 OK] GFE github.com [200 OK] GitHub reddit.com [200 OK] React",
        "192.168.1.1 [200 OK] RouterOS",
        "192.168.1.1 RouterOS 192.168.1.10 Apache",
        "google.com [200 OK] github.com [200 OK] example.com [200 OK]",
        "Logging complete",
        "JSON file saved",
        "XML log created",
        "Using proxy 127.0.0.1:8080",
        "User-Agent changed",
        "Header added successfully",
        "Cookie loaded",
        "Authenticated successfully",
        "apache wordpress drupal joomla jquery php",
        "wordpress.rb wordpress_backup.rb",
        "Plugin: WordPress Author: Brendan Coles",
        "WordPress[6.0]",
        "Apache, WordPress, JQuery",
        "WordPress detected",
        "example.com [200 OK]",
        "Errors hidden",
        "Redirect followed",
        "Maximum redirects: 5",
        "Using 50 threads",
        "Timeout set to 10 seconds",
        "Waiting 2 seconds",
        "Debugging enabled",
        "Aggressive scan started Verbose output enabled Results saved to scan.json",
        "https://wordpress.org [200 OK] WordPress, PHP[8.0], JQuery, Nginx",
        "Joomla, PHP, Apache",
        "Nginx, HTML5"

    ]
}

# ==========================================
# CONVERT TO DATAFRAME
# ==========================================

df = pd.DataFrame(data)

# ==========================================
# INPUT AND OUTPUT
# ==========================================

X = df["command"]
y = df["output"]

# ==========================================
# SPLIT DATA
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ==========================================
# CREATE MODEL PIPELINE
# ==========================================

model = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('classifier', KNeighborsClassifier(n_neighbors=1))
])

# ==========================================
# TRAIN MODEL
# ==========================================

model.fit(X_train, y_train)

# ==========================================
# CHECK ACCURACY
# ==========================================

accuracy = model.score(X_test, y_test)

print("="*50)
print("MODEL TRAINED SUCCESSFULLY")
print("="*50)

print(f"\nAccuracy: {accuracy * 100:.2f}%")

# ==========================================
# SAVE MODEL
# ==========================================

joblib.dump(model, "whatweb_model.pkl")

print("\nModel saved as whatweb_model.pkl")

# ==========================================
# PREDICTION LOOP
# ==========================================

print("\n==============================")
print("WHATWEB AI PREDICTION SYSTEM")
print("==============================")

while True:

    user_input = input("\nEnter WhatWeb Command (or type exit): ")

    if user_input.lower() == "exit":
        print("Exiting...")
        break

    prediction = model.predict([user_input])

    print("\nPredicted Output:")
    print(prediction[0])

# ==========================================
# END
# ==========================================

==================================================
MODEL TRAINED SUCCESSFULLY
==================================================

Accuracy: 0.00%

Model saved as whatweb_model.pkl

==============================
WHATWEB AI PREDICTION SYSTEM
==============================

Enter WhatWeb Command (or type exit):  whatweb -I wordpress

Predicted Output:
Plugin: WordPress Author: Brendan Coles

Enter WhatWeb Command (or type exit):  whatweb --wait 2 example.com

Predicted Output:
Waiting 2 seconds

Enter WhatWeb Command (or type exit):  whatweb https://google.com

Predicted Output:
https://google.com [200 OK] GFE, HTML5

Enter WhatWeb Command (or type exit):  whatweb -v example.com

Predicted Output:
http://example.com [200 OK] Apache, HTML5

Enter WhatWeb Command (or type exit):  whatweb -a 4 example.com

Predicted Output:
http://example.com [200 OK] Apache, HTML5

Enter WhatWeb Command (or type exit):  exit

Exiting...

In [14]:
# ==========================================================
# WHATWEB AI CYBERSECURITY ASSISTANT
# ==========================================================

# Install Required Libraries
# pip install pandas scikit-learn joblib

import pandas as pd
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multioutput import MultiOutputClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

# ==========================================================
# LOAD DATASET
# ==========================================================

# Replace with your dataset path
df = pd.read_csv("whatweb_multi_vulnerability_dataset.csv")

print("="*60)
print("DATASET LOADED SUCCESSFULLY")
print("="*60)

print(df.head())

# ==========================================================
# INPUT AND OUTPUT COLUMNS
# ==========================================================

X = df["Input"]

# Multiple outputs
y = df[[
    "Output",
    "Analyse",
    "Vulnerabilities",
    "NextStep"
]]

# ==========================================================
# TRAIN TEST SPLIT
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ==========================================================
# CREATE MODEL
# ==========================================================

model = Pipeline([

    ("tfidf", TfidfVectorizer()),

    ("classifier", MultiOutputClassifier(
        MultinomialNB()
    ))

])

# ==========================================================
# TRAIN MODEL
# ==========================================================

print("\nTraining Model...\n")

model.fit(X_train, y_train)

print("MODEL TRAINED SUCCESSFULLY")

# ==========================================================
# MODEL ACCURACY
# ==========================================================

accuracy = model.score(X_test, y_test)

print(f"\nModel Accuracy: {accuracy * 100:.2f}%")

# ==========================================================
# SAVE MODEL
# ==========================================================

joblib.dump(model, "whatweb_ai_model.pkl")

print("\nModel Saved As: whatweb_ai_model.pkl")

# ==========================================================
# LOAD MODEL
# ==========================================================

loaded_model = joblib.load("whatweb_ai_model.pkl")

# ==========================================================
# PREDICTION LOOP
# ==========================================================

print("\n" + "="*60)
print("WHATWEB AI CYBERSECURITY ASSISTANT")
print("="*60)

while True:

    user_input = input("\nEnter WhatWeb Command (type exit to stop): ")

    if user_input.lower() == "exit":
        print("\nExiting AI Assistant...")
        break

    # Predict
    prediction = loaded_model.predict([user_input])

    # Extract predictions
    output_prediction = prediction[0][0]
    analyse_prediction = prediction[0][1]
    vulnerability_prediction = prediction[0][2]
    nextstep_prediction = prediction[0][3]

    # ======================================================
    # DISPLAY RESULTS
    # ======================================================

    print("\n" + "="*60)
    print("AI PREDICTION RESULT")
    print("="*60)

    print(f"\nINPUT COMMAND:")
    print(user_input)

    print(f"\nOUTPUT:")
    print(output_prediction)

    print(f"\nANALYSE:")
    print(analyse_prediction)

    print(f"\nVULNERABILITIES:")
    print(vulnerability_prediction)

    print(f"\nNEXT STEP:")
    print(nextstep_prediction)

    print("\n" + "="*60)

# ==========================================================
# END
# ==========================================================

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:302: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  self.y_type_ = type_of_target(y, input_name="y")
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:359: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_is_multilabel = type_of_target(y).startswith("multilabel")
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:528: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y)

============================================================
DATASET LOADED SUCCESSFULLY
============================================================
                                           Input  \
0                     whatweb -a 3 wordpress.org
1                          whatweb -v reddit.com
2                          whatweb -v drupal.org
3  whatweb --open-timeout 10 testphp.vulnweb.com
4                        whatweb -a 4 reddit.com

                                Output  \
0                     IIS, PHP, JQuery
1      200 OK, IP Address Found, Nginx
2  200 OK, IP Address Found, LiteSpeed
3            Timeout set to 10 seconds
4              Nginx, Bootstrap, React

                                           Analyse  \
0  Aggressive scan identified backend technologies
1                         Verbose output collected
2                         Verbose output collected
3                    Connection timeout configured
4                Maximum aggressive scan completed

                                     Vulnerabilities  \
0  Outdated CMS Version, Weak Authentication, SQL...
1  Command Injection, Weak SSL/TLS Configuration,...
2             Directory Traversal, Command Injection
3  Sensitive Information Disclosure, Directory Tr...
4          SQL Injection, Cross-Site Scripting (XSS)

                      NextStep
0     Generate security report
1     Generate security report
2       Perform manual testing
3  Review server configuration
4                   Run WPScan

Training Model...

MODEL TRAINED SUCCESSFULLY

Model Accuracy: 0.00%

Model Saved As: whatweb_ai_model.pkl

============================================================
WHATWEB AI CYBERSECURITY ASSISTANT
============================================================

Enter WhatWeb Command (type exit to stop):  exit

Exiting AI Assistant...

In [4]:
df.head()

,Input,Output,Analyse,Vulnerabilities,NextStep
0,whatweb -a 3 wordpress.org,"IIS, PHP, JQuery",Aggressive scan identified backend technologies,"Outdated CMS Version, Weak Authentication, SQL...",Generate security report
1,whatweb -v reddit.com,"200 OK, IP Address Found, Nginx",Verbose output collected,"Command Injection, Weak SSL/TLS Configuration,...",Generate security report
2,whatweb -v drupal.org,"200 OK, IP Address Found, LiteSpeed",Verbose output collected,"Directory Traversal, Command Injection",Perform manual testing
3,whatweb --open-timeout 10 testphp.vulnweb.com,Timeout set to 10 seconds,Connection timeout configured,"Sensitive Information Disclosure, Directory Tr...",Review server configuration
4,whatweb -a 4 reddit.com,"Nginx, Bootstrap, React",Maximum aggressive scan completed,"SQL Injection, Cross-Site Scripting (XSS)",Run WPScan

In [6]:
df.tail()

,Input,Output,Analyse,Vulnerabilities,NextStep
595,whatweb reddit.com,"IIS, HTML5",IIS web server detected,"Security Misconfiguration, Broken Access Contr...",Run WPScan
596,whatweb --no-errors example.com,Errors hidden,Error suppression enabled,"Open Redirect, CSRF, Sensitive Information Dis...",Perform manual testing
597,whatweb --debug wordpress.org,Debugging enabled,Debug mode activated,"Sensitive Information Disclosure, Broken Acces...",Analyze HTTP headers
598,whatweb -p apache github.com,apache[Detected],apache plugin detected,"Sensitive Information Disclosure, Broken Acces...",Perform port scanning
599,whatweb --follow-redirect always example.com,Redirect followed successfully,Redirect behavior analyzed,"Clickjacking, Remote Code Execution, Outdated ...",Run WPScan

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Input            600 non-null    object
 1   Output           600 non-null    object
 2   Analyse          600 non-null    object
 3   Vulnerabilities  600 non-null    object
 4   NextStep         600 non-null    object
dtypes: object(5)
memory usage: 23.6+ KB

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
df.plot
plt.show()

In [12]:
df["Vulnerabilities"]

0      Outdated CMS Version, Weak Authentication, SQL...
1      Command Injection, Weak SSL/TLS Configuration,...
2                 Directory Traversal, Command Injection
3      Sensitive Information Disclosure, Directory Tr...
4              SQL Injection, Cross-Site Scripting (XSS)
                             ...
595    Security Misconfiguration, Broken Access Contr...
596    Open Redirect, CSRF, Sensitive Information Dis...
597    Sensitive Information Disclosure, Broken Acces...
598    Sensitive Information Disclosure, Broken Acces...
599    Clickjacking, Remote Code Execution, Outdated ...
Name: Vulnerabilities, Length: 600, dtype: object

In [17]:
# ==========================================================
# WHATWEB AI CYBERSECURITY ASSISTANT
# EXACT MATCH + AI PREDICTION
# ==========================================================

import pandas as pd
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline

# ==========================================================
# LOAD DATASET
# ==========================================================

df = pd.read_csv("whatweb_multi_vulnerability_dataset.csv")

print("="*60)
print("DATASET LOADED SUCCESSFULLY")
print("="*60)

# ==========================================================
# INPUT AND OUTPUT
# ==========================================================

X = df["Input"]

y_output = df["Output"]
y_analyse = df["Analyse"]
y_vulnerability = df["Vulnerabilities"]
y_nextstep = df["NextStep"]

# ==========================================================
# CREATE SEPARATE MODELS
# ==========================================================

output_model = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("classifier", KNeighborsClassifier(n_neighbors=1))
])

analyse_model = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("classifier", KNeighborsClassifier(n_neighbors=1))
])

vulnerability_model = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("classifier", KNeighborsClassifier(n_neighbors=1))
])

nextstep_model = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("classifier", KNeighborsClassifier(n_neighbors=1))
])

# ==========================================================
# TRAIN MODELS
# ==========================================================

print("\nTraining Models...\n")

output_model.fit(X, y_output)
analyse_model.fit(X, y_analyse)
vulnerability_model.fit(X, y_vulnerability)
nextstep_model.fit(X, y_nextstep)

print("MODELS TRAINED SUCCESSFULLY")

# ==========================================================
# SAVE MODELS
# ==========================================================

joblib.dump(output_model, "output_model.pkl")
joblib.dump(analyse_model, "analyse_model.pkl")
joblib.dump(vulnerability_model, "vulnerability_model.pkl")
joblib.dump(nextstep_model, "nextstep_model.pkl")

print("\nMODELS SAVED SUCCESSFULLY")

# ==========================================================
# AI ASSISTANT
# ==========================================================

print("\n" + "="*60)
print("WHATWEB AI CYBERSECURITY ASSISTANT")
print("="*60)

while True:

    user_input = input("\nEnter WhatWeb Command (type exit to stop): ")

    if user_input.lower() == "exit":
        print("\nExiting...")
        break

    # ======================================================
    # EXACT MATCH SEARCH
    # ======================================================

    exact_match = df[df["Input"] == user_input]

    if len(exact_match) > 0:

        print("\n" + "="*60)
        print("EXACT MATCH FOUND")
        print("="*60)

        row = exact_match.iloc[0]

        print("\nINPUT COMMAND:")
        print(user_input)

        print("\nOUTPUT:")
        print(row["Output"])

        print("\nANALYSE:")
        print(row["Analyse"])

        print("\nVULNERABILITIES:")
        print(row["Vulnerabilities"])

        print("\nNEXT STEP:")
        print(row["NextStep"])

    else:

        # ==================================================
        # AI PREDICTION
        # ==================================================

        output_prediction = output_model.predict([user_input])[0]
        analyse_prediction = analyse_model.predict([user_input])[0]
        vulnerability_prediction = vulnerability_model.predict([user_input])[0]
        nextstep_prediction = nextstep_model.predict([user_input])[0]

        print("\n" + "="*60)
        print("AI PREDICTION RESULT")
        print("="*60)

        print("\nINPUT COMMAND:")
        print(user_input)

        print("\nOUTPUT:")
        print(output_prediction)

        print("\nANALYSE:")
        print(analyse_prediction)

        print("\nVULNERABILITIES:")
        print(vulnerability_prediction)

        print("\nNEXT STEP:")
        print(nextstep_prediction)

print("\nSYSTEM STOPPED")

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  y_type = type_of_target(y, input_name="y")

============================================================
DATASET LOADED SUCCESSFULLY
============================================================

Training Models...

MODELS TRAINED SUCCESSFULLY

MODELS SAVED SUCCESSFULLY

============================================================
WHATWEB AI CYBERSECURITY ASSISTANT
============================================================

Enter WhatWeb Command (type exit to stop):  whatweb --debug wordpress.org

============================================================
AI PREDICTION RESULT
============================================================

INPUT COMMAND:
whatweb --debug wordpress.org

OUTPUT:
Debugging enabled

ANALYSE:
Debug mode activated

VULNERABILITIES:
Weak SSL/TLS Configuration, Insecure Headers

NEXT STEP:
Check SSL configuration

Enter WhatWeb Command (type exit to stop):  whatweb --debug wordpress.org

============================================================
AI PREDICTION RESULT
============================================================

INPUT COMMAND:
whatweb --debug wordpress.org

OUTPUT:
Debugging enabled

ANALYSE:
Debug mode activated

VULNERABILITIES:
Weak SSL/TLS Configuration, Insecure Headers

NEXT STEP:
Check SSL configuration

Enter WhatWeb Command (type exit to stop):  exit

Exiting...

SYSTEM STOPPED

In [16]:
df.tail()

,Input,Output,Analyse,Vulnerabilities,NextStep
595,whatweb reddit.com,"IIS, HTML5",IIS web server detected,"Security Misconfiguration, Broken Access Contr...",Run WPScan
596,whatweb --no-errors example.com,Errors hidden,Error suppression enabled,"Open Redirect, CSRF, Sensitive Information Dis...",Perform manual testing
597,whatweb --debug wordpress.org,Debugging enabled,Debug mode activated,"Sensitive Information Disclosure, Broken Acces...",Analyze HTTP headers
598,whatweb -p apache github.com,apache[Detected],apache plugin detected,"Sensitive Information Disclosure, Broken Acces...",Perform port scanning
599,whatweb --follow-redirect always example.com,Redirect followed successfully,Redirect behavior analyzed,"Clickjacking, Remote Code Execution, Outdated ...",Run WPScan

In [ ]:
# ==========================================================
# WHATWEB CYBERSECURITY ASSISTANT
# 100% ACCURATE DATASET SEARCH SYSTEM
# ==========================================================

import pandas as pd
from difflib import get_close_matches

# ==========================================================
# LOAD DATASET
# ==========================================================

df = pd.read_csv("whatweb_multi_vulnerability_dataset.csv")

print("="*60)
print("DATASET LOADED SUCCESSFULLY")
print("="*60)

# ==========================================================
# AI ASSISTANT
# ==========================================================

while True:

    user_input = input("\nEnter WhatWeb Command (type exit to stop): ")

    if user_input.lower() == "exit":
        print("\nExiting...")
        break

    # ======================================================
    # EXACT MATCH
    # ======================================================

    result = df[df["Input"].str.lower() == user_input.lower()]

    if not result.empty:

        row = result.iloc[0]

        print("\n" + "="*60)
        print("MATCH FOUND")
        print("="*60)

        print("\nINPUT:")
        print(row["Input"])

        print("\nOUTPUT:")
        print(row["Output"])

        print("\nANALYSE:")
        print(row["Analyse"])

        print("\nVULNERABILITIES:")
        print(row["Vulnerabilities"])

        print("\nNEXT STEP:")
        print(row["NextStep"])

    else:

        # ==================================================
        # SIMILAR COMMAND SEARCH
        # ==================================================

        commands = df["Input"].tolist()

        similar = get_close_matches(user_input, commands, n=1)

        if similar:

            similar_result = df[df["Input"] == similar[0]].iloc[0]

            print("\n" + "="*60)
            print("SIMILAR COMMAND FOUND")
            print("="*60)

            print("\nClosest Match:")
            print(similar[0])

            print("\nOUTPUT:")
            print(similar_result["Output"])

            print("\nANALYSE:")
            print(similar_result["Analyse"])

            print("\nVULNERABILITIES:")
            print(similar_result["Vulnerabilities"])

            print("\nNEXT STEP:")
            print(similar_result["NextStep"])

        else:

            print("\nNo matching command found.")

print("\nSYSTEM STOPPED")

============================================================
DATASET LOADED SUCCESSFULLY
============================================================

Enter WhatWeb Command (type exit to stop):  whatweb reddit.com

============================================================
MATCH FOUND
============================================================

INPUT:
whatweb reddit.com

OUTPUT:
Apache, HTML5

ANALYSE:
Apache web server detected

VULNERABILITIES:
Insecure Headers, Security Misconfiguration, Weak Authentication, Outdated CMS Version, Remote Code Execution

NEXT STEP:
Review server configuration

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns